name: "Hello Actions"
description: "Greet someone"
author: "Vital D."


inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "world"

runs:
    using: "docker"
    image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"

